---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Install system packages
      yum: name={{ item }} update_cache=yes
      with_items: "{{ system_packages }}"

    - name: Create directory for app
      file: path={{ install_root }}/{{ project_name }} state=directory

    - name: Create Mysql configuration file
      template: src=my.cnf.j2 dest=/etc/my.cnf
      notify:
      - restart mysql

    - name: Start Mysql Service
      service: name=mysql state=started enabled=true

    - name: Create Mysql Database
      mysql_db: name={{ db_name }} state=present

    - name: Create Mysql DB User
      mysql_user: name={{ db_user }} password={{ db_password }} priv=*.*:ALL host='%' state=present

    - name: remove default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent

- include: deploy.yml

# vim:ft=ansible:
